import { User } from '../models/user';

export const users: User[] = [
  {
    uid: '1',
    firstName: 'rana',
    lastName: 'obied',
    email: 'ranasobeid95@gmail.com',
    password: '12345678rA',
    emailVerified: false,
  },
  {
    uid: '2',
    firstName: 'asem',
    lastName: 'hasan',
    email: 'asem123@gmail.com',
    password: '12345678rA',
    emailVerified: false,
  },
];

export const tests: any[] = [
  {
    userId: 19,
    waterIntake: 10,
    alcoholDrinks: 9,
    exercise: 5,
    dietChange: 'None',
    createdAt: new Date('5/4/21 10:27'),
    cardPhoto: '',
    results: {
      overallHealth: 87,
      healthText: '…',
      bacteria: 93,
      blood: 91,
      leukocytes: 90,
      immunity: 91,
      immunityText: '…',
      pH_Value: 5.5,
      pH_Score: 61,
      glucose: 100,
      ketones: 100,
      nutrition: 87,
      nutritionText: '…',
      hydration: 46,
      hydrationText: '…',
      gravity: 90,
      bilirubin: 100,
      urobilinogen: 100,
      liverHealth: 100,
      liverText: '…',
      proteins: 100,
      kidney: 100,
      kidneyText: '…',
      rec_1: 'recommendation',
    },
  },
  {
    userId: 19,
    waterIntake: 10,
    alcoholDrinks: 9,
    exercise: 5,
    dietChange: 'None',
    createdAt: new Date('5/5/21 10:27'),
    cardPhoto: '',
    results: {
      overallHealth: 88,
      healthText: '…',
      bacteria: 100,
      blood: 91,
      leukocytes: 84,
      immunity: 92,
      immunityText: '…',
      pH_Value: 6.1,
      pH_Score: 74,
      glucose: 100,
      ketones: 100,
      nutrition: 91,
      nutritionText: '…',
      hydration: 46,
      gravity: 80,
      hydrationText: '…',
      bilirubin: 100,
      urobilinogen: 100,
      liverHealth: 100,
      liverText: '…',
      proteins: 100,
      kidney: 100,
      kidneyText: '…',
      rec_1: 'recommendation',
    },
  },
];

export const resultsMock = [
  {
    createdAt: new Date('5/4/21 10:27'),
    overallHealth: 87,
    healthText: '…',
    bacteria: 93,
    blood: 91,
    leukocytes: 90,
    immunity: 91,
    immunityText: '…',
    pH_Value: 5.5,
    pH_Score: 61,
    glucose: 100,
    ketones: 100,
    nutrition: 87,
    nutritionText: '…',
    hydration: 46,
    hydrationText: '…',
    gravity: 90,
    bilirubin: 100,
    urobilinogen: 100,
    liverHealth: 100,
    liverText: '…',
    proteins: 100,
    kidney: 100,
    kidneyText: '…',
    rec_1: 'recommendation',
  },
];
