export const ROUTES = {
  SIGN_IN: 'sign-in',
  SIGN_UP: 'sign-up',
  SIGN_OUT: 'sign-out',
  RESET_PASSWORD: 'reset-password',
  PAGE_NOT_FOUND: '404',
  HOME_PAGE: 'home',
  LANDING_PAGE: '',
  ABOUT_MIDO: 'mido',
  RESULTS_PAGE: 'results',
  NEW_TEST_PAGE: 'new-test',
  PROFILE_PAGE: 'profile',
  VERIFY_EMAIL: 'verify-email',
  CUSTOM_EMAIL: 'custom-email',
  SETTING_ACCOUNT: '/profile/setting',
  QUICK_START: 'quick-start',
};
